services:
  - type: web
    name: simple-split-payer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
